### ISSUE TITLE
Use with Drive/Volumes icon

### ISSUE THREAD

**Issue by ConnorJD94** [lgarron/folderify#66]
I've been loving using this with folders, but I've been wondering if there is a way to use it with the Drive/Volumes (attached) icon as the base instead? 

[](url)
<img width="255" alt="Screen Shot 2023-01-16 at 11 45 56 am" src="https://user-images.githubusercontent.com/67985422/212581532-27a457d5-6eb8-48b2-969b-34daf9898d28.png">

**Comment by lgarron** [comment]
macOS doesn't really do engraved of customized disk icons. I'd suggest using a perspective warp tool to fit an icon over a the disk.

I consider this outside the scope of `folderify`, so I'm going to close this for now. But since I've started getting more requests for non-folder outputs, I've created a tag and will keep it in mind for future rewrites.
